<?php

/**
 * @file
 * Contains unittestexample.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function unittestexample_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the unittestexample module.
    case 'help.page.unittestexample':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Unit test case example') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function unittestexample_theme() {
  return [
    'unittestexample' => [
      'render element' => 'children',
    ],
  ];
}
